// @AnubisCheatz
//
// sdk genrated by @crusher_14
//
// https://t.me/AnubisCheatz

#pragma once

namespace SDK
{

// Object: Enum ModularGameplay.EGameFrameworkAddComponentFlags
enum class EGameFrameworkAddComponentFlags : uint8_t
{
	None = 0,
	AddUnique = 1,
	AddIfNotChild = 2,
	UseAutoGeneratedName = 4,
	EGameFrameworkAddComponentFlags_MAX = 5
};

// Object: ScriptStruct ModularGameplay.ActorInitStateChangedParams
// Size: 0x20 (Inherited: 0x0)
struct FActorInitStateChangedParams
{
	struct AActor* OwningActor; // 0x0(0x8)
	struct FName FeatureName; // 0x8(0x8)
	struct UObject* Implementer; // 0x10(0x8)
	struct FGameplayTag FeatureState; // 0x18(0x8)
};

} // namespace SDK
